"""empty message

Revision ID: 9f8ede63f571
Revises: 237398855c05
Create Date: 2025-07-17 15:44:25.375296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f8ede63f571"
down_revision: Union[str, Sequence[str], None] = "237398855c05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cartitems", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.drop_column("cartitems", "added_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cartitems",
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("cartitems", "created_at")
    # ### end Alembic commands ###
